# Generated by Django 6.0 on 2025-12-12 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartieCommune',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('surface', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=50)),
                ('valeur_consommee', models.FloatField()),
                ('cout', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('partie_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='consumption.partiecommune')),
            ],
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('localisation', models.CharField(max_length=255)),
                ('date_installation', models.DateField()),
                ('type_compteur', models.CharField(max_length=50)),
                ('etat_compteur', models.CharField(max_length=50)),
                ('partie_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='consumption.partiecommune')),
            ],
        ),
        migrations.CreateModel(
            name='Releve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valeur', models.FloatField()),
                ('date_releve', models.DateTimeField()),
                ('methode_releve', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('est_corrige', models.BooleanField(default=False)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='consumption.compteur')),
            ],
            options={
                'ordering': ['-date_releve'],
                'unique_together': {('compteur', 'date_releve')},
            },
        ),
    ]
