# Generated by Django 6.0 on 2026-01-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='seuil_alerte',
            field=models.FloatField(default=200.0),
        ),
    ]
