# Generated by Django 6.0 on 2025-12-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumption', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('niveau_priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=10)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En Cours'), ('RESOLUE', 'Résolue'), ('REJETEE', 'Rejetée')], default='OUVERTE', max_length=10)),
                ('compteur_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumption.compteur')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='users.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_intervention', models.DateTimeField()),
                ('rapport', models.TextField(help_text="Description détaillée de l'intervention et des résolutions.")),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.technicienmaintenance')),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='claims.reclamation')),
            ],
        ),
    ]
