# Generated by Django 6.0 on 2025-12-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='type_reclamation',
            field=models.CharField(default='Électricité', max_length=50),
        ),
    ]
