# Generated by Django 6.0 on 2026-01-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_reclamation_type_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='rapport',
            field=models.TextField(blank=True, help_text='Description détaillée...', null=True),
        ),
    ]
