# Generated by Django 6.0 on 2025-12-12 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueConsommation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=50)),
                ('valeur_moyenne', models.FloatField()),
                ('valeur_maximale', models.FloatField()),
                ('cout_total', models.FloatField()),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('partie_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='consumption.partiecommune')),
            ],
            options={
                'unique_together': {('periode', 'partie_commune')},
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_rapport', models.CharField(max_length=100)),
                ('format_export', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=10)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_chemin', models.CharField(blank=True, max_length=255, null=True)),
                ('statistiques_incluses', models.ManyToManyField(to='reports.statistiqueconsommation')),
            ],
        ),
    ]
