# Generated by Django 6.0 on 2025-12-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeuilAlerte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_alerte', models.CharField(choices=[('SURCONS', 'Surconsommation'), ('ANOMALIE_RELEVE', 'Incohérence de relevé')], default='SURCONS', max_length=50)),
                ('valeur_seuil', models.FloatField(help_text='Valeur absolue ou pourcentage de dépassement.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumption.compteur')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('est_traitee', models.BooleanField(default=False)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='consumption.compteur')),
                ('seuil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.seuilalerte')),
            ],
        ),
    ]
